spring:
  datasource:
    url: jdbc:mysql://localhost:3308/shop
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: user
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: Gu/UekFR3sFv+LZ8q7sVzIoFD2RozVmx0VSYOviqVrY=
start: 1/4/2024
